#!/bin/bash
# Quick Start Script for Unstop Crawler

echo "========================================="
echo "Unstop Hackathon Scraper - Quick Start"
echo "========================================="
echo ""

# Activate virtual environment
echo "Activating virtual environment..."
source .venv/bin/activate

# Show available commands
echo ""
echo "✨ AVAILABLE COMMANDS ✨"
echo "========================================="
echo ""
echo "📥 SCRAPING OPTIONS:"
echo ""
echo "1. Daily update (only NEW hackathons):"
echo "   python manage.py scrape_unstop"
echo ""
echo "2. Test scrape (3 new hackathons):"
echo "   python manage.py scrape_unstop --limit 3"
echo ""
echo "3. Full rescrape (update all existing):"
echo "   python manage.py scrape_unstop --force-rescrape"
echo ""
echo "4. Start from specific page:"
echo "   python manage.py scrape_unstop --start-page 5"
echo ""
echo "5. Skip first N pages:"
echo "   python manage.py scrape_unstop --skip-pages 10"
echo ""
echo "6. Skip first N hackathons:"
echo "   python manage.py scrape_unstop --skip-hackathons 20"
echo ""
echo "7. Advanced - combine options:"
echo "   python manage.py scrape_unstop --start-page 5 --limit 10"
echo ""
echo "========================================="
echo ""
echo "📤 EXPORT OPTIONS:"
echo ""
echo "8. Export to JSON:"
echo "   python manage.py export_hackathons --format json --output hackathons.json"
echo ""
echo "9. Export to CSV:"
echo "   python manage.py export_hackathons --format csv --output hackathons.csv"
echo ""
echo "========================================="
echo ""
echo "🔧 ADMIN OPTIONS:"
echo ""
echo "10. Create admin user (for web interface):"
echo "    python manage.py createsuperuser"
echo ""
echo "11. Start Django server (view in browser):"
echo "    python manage.py runserver"
echo "    Then open: http://127.0.0.1:8000/admin/"
echo ""
echo "========================================="
echo ""
echo "💡 QUICK TIPS:"
echo "   • Scraper skips existing hackathons by default"
echo "   • Uses your Chromium Profile 2 for scraping"
echo "   • Extracts: dates, contacts, official websites"
echo "   • Auto-stops when all new hackathons found"
echo ""
echo "📚 Documentation: See FINAL_SUMMARY.md"
echo ""
echo "========================================="
echo ""
echo "Run a test scrape now? (y/n)"
read -r response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo ""
    echo "Running test scrape with 3 new hackathons..."
    echo ""
    python manage.py scrape_unstop --limit 3
    echo ""
    echo "✅ Done! To export the data, run:"
    echo "   python manage.py export_hackathons --format json --output test.json"
    echo ""
fi
