# Generated by Django 5.2.7 on 2025-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('organizer', models.CharField(blank=True, max_length=500, null=True)),
                ('registered_count', models.CharField(blank=True, max_length=100, null=True)),
                ('about_content', models.TextField(blank=True, null=True)),
                ('organizer_contact', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
