# Generated by Django 5.2.7 on 2025-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='important_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='official_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
