# Generated by Django 5.2.7 on 2025-11-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_hackathon_important_dates_hackathon_official_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='impression_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
