# Generated by Django 5.2.7 on 2025-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_hackathon_impression_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('organizer', models.CharField(blank=True, max_length=500, null=True)),
                ('registered_count', models.CharField(blank=True, max_length=100, null=True)),
                ('impression_count', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_count', models.CharField(blank=True, max_length=100, null=True)),
                ('about_content', models.TextField(blank=True, null=True)),
                ('organizer_contact', models.TextField(blank=True, null=True)),
                ('important_dates', models.TextField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('prizes', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
