# Generated by Django 5.2.7 on 2025-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_devfoliohackathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='devfoliohackathon',
            name='discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devfoliohackathon',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devfoliohackathon',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devfoliohackathon',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
