# Generated by Django 5.2.7 on 2025-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_devfoliohackathon_discord_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevpostHackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('organizer', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('participants_count', models.CharField(blank=True, max_length=100, null=True)),
                ('projects_count', models.CharField(blank=True, max_length=100, null=True)),
                ('about_content', models.TextField(blank=True, null=True)),
                ('organizer_contact', models.TextField(blank=True, null=True)),
                ('important_dates', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('prizes', models.TextField(blank=True, null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('themes', models.TextField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
