# Generated by Django 5.2.7 on 2025-11-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_devposthackathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devposthackathon',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='important_dates',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='location',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='official_website',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='prizes',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='projects_count',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='devposthackathon',
            name='themes',
        ),
    ]
