# Generated by Django 5.2.8 on 2025-11-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DorkQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('snippet', models.TextField(blank=True)),
                ('position', models.IntegerField()),
                ('page_number', models.IntegerField(default=1)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('dork_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawler.dorkquery')),
            ],
            options={
                'ordering': ['dork_query', 'page_number', 'position'],
                'unique_together': {('dork_query', 'url')},
            },
        ),
    ]
