# Generated by Django 5.2.7 on 2026-01-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.URLField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('depth_level', models.IntegerField(default=0)),
                ('posts_scraped', models.IntegerField(default=0)),
                ('profiles_scraped', models.IntegerField(default=0)),
                ('emails_collected', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('max_posts', models.IntegerField(default=1000)),
                ('max_depth', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_discovered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(unique=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('scraped', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_from_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_posts', to='contacts.profile')),
            ],
            options={
                'ordering': ['-comment_count', '-created_at'],
                'indexes': [models.Index(fields=['scraped', 'comment_count'], name='contacts_po_scraped_e13db5_idx'), models.Index(fields=['post_url'], name='contacts_po_post_ur_bc0b8f_idx')],
            },
        ),
    ]
